version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    links:
      - gitea
    volumes:
      - /home/lightdiscord/.caddy/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  gitea:
    image: gitea/gitea:latest
    ports:
      - "10022:22"
    volumes:
      - /var/lib/gitea:/data
    restart: on-failure
